### ISSUE TITLE
add elemetric to header

### ISSUE THREAD

**Issue by Practical-DQ** [SimplyVisual/youlazydawg#35]
get the header in the traditional yellow and blue with electric
top header should dissappear when the user scrolls down
second header with points should remain visible at all time,
points header should reflect point score at where you are in the timeline. so scrolling down is like walking back in time

**Comment by danielkagemann** [comment]
> get the header in the traditional yellow and blue with electric
nope. looks ugly

> top header should dissappear when the user scrolls down
nope. because navigation elements now in there

> second header with points should remain visible at all time,
points header should reflect point score at where you are in the timeline. so scrolling down is like walking back in time
yes. working on that feature

**Comment by danielkagemann** [comment]
i think this is done with the upcoming version
